_templates:
  - &rake
    command: "bin/rake"
    plugins:
      docker-compose#v2.6.0:
        run: app
        config: .buildkite/docker-compose.yml
    timeout_in_minutes: 10

steps:
  - <<: *rake
    name: "JRuby"
    env:
      RUBY_IMAGE: "jruby:9.2.7.0" # https://github.com/jruby/jruby/issues/5863
    parallelism: 20
